# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e272f6cb0c66e2cfc97a6547e5e3ce85a66c96d330ca5de985bf692f35d2b6e28bccef7d458aac6e62119af3b181ba5d32acc3fe791500fd8debcc4c30145fd5

test:
  secret_key_base: 2068a789f4f78e297a8307c169bb5fa6c1bcd0fa0fadafa7dc9e417fffff11eb118442dff598c8f0af0ad51ca924246ed4f05abf4501382d2d8b98cae0981173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
